/**
 * Case File: public queries and mutations.
 *
 * A Case File is a one-page raise brief generated by AI, combining:
 *   - the user's pay gap figure
 *   - their strongest logged wins
 *   - their best rehearsed lines (from completed Rehearsal Room sessions)
 *
 * Generated natively in the user's preferred language.
 * Exported via a print stylesheet; shared via an opaque share token link.
 *
 * The AI generation logic lives in caseFileAction.ts (internalAction) to
 * prevent circular type-inference.
 */
import { mutation, query, internalMutation } from './_generated/server'
import { internal } from './_generated/api'
import { v } from 'convex/values'
import type { Id } from './_generated/dataModel'

// ---------------------------------------------------------------------------
// Auth helper
// ---------------------------------------------------------------------------

async function requireUser(ctx: { auth: { getUserIdentity: () => Promise<{ subject: string } | null> }; db: any }) {
  const identity = await ctx.auth.getUserIdentity()
  if (!identity) throw new Error('Not authenticated.')

  const user = await ctx.db
    .query('users')
    .withIndex('by_clerk_id', (q: any) => q.eq('clerkId', identity.subject))
    .unique()

  if (!user) throw new Error('User record not found. Complete onboarding first.')
  return user
}

// ---------------------------------------------------------------------------
// Queries
// ---------------------------------------------------------------------------

/**
 * List the calling user's case files, most recent first.
 */
export const listCaseFiles = query({
  args: {
    limit: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const identity = await ctx.auth.getUserIdentity()
    if (!identity) return []

    const user = await ctx.db
      .query('users')
      .withIndex('by_clerk_id', (q: any) => q.eq('clerkId', identity.subject))
      .unique()
    if (!user) return []

    return ctx.db
      .query('caseFiles')
      .withIndex('by_user_created', (q: any) => q.eq('userId', user._id))
      .order('desc')
      .take(args.limit ?? 50)
  },
})

/**
 * Get a single case file by ID. Returns null if the caller does not own it.
 */
export const getCaseFile = query({
  args: { caseFileId: v.id('caseFiles') },
  handler: async (ctx, args) => {
    const identity = await ctx.auth.getUserIdentity()
    if (!identity) return null

    const cf = await ctx.db.get(args.caseFileId)
    if (!cf) return null

    const user = await ctx.db
      .query('users')
      .withIndex('by_clerk_id', (q: any) => q.eq('clerkId', identity.subject))
      .unique()
    if (!user || cf.userId !== user._id) return null

    return cf
  },
})

/**
 * Get a case file by its public share token. No auth required.
 * Returns null if the token is invalid or the case file is not yet ready.
 */
export const getCaseFileByToken = query({
  args: { shareToken: v.string() },
  handler: async (ctx, args) => {
    const cf = await ctx.db
      .query('caseFiles')
      .withIndex('by_share_token', (q: any) => q.eq('shareToken', args.shareToken))
      .unique()

    if (!cf || cf.status !== 'ready') return null
    return cf
  },
})

// ---------------------------------------------------------------------------
// Mutations
// ---------------------------------------------------------------------------

/**
 * Create a new case file and schedule AI generation.
 * Returns the case file ID immediately; the client polls `getCaseFile` for
 * status changes ('generating' → 'ready' | 'error').
 */
export const requestCaseFileGeneration = mutation({
  args: {},
  handler: async (ctx): Promise<Id<'caseFiles'>> => {
    const user = await requireUser(ctx as any)

    // Use the user's most recent pay gap profile if one exists.
    const payGapProfile = await ctx.db
      .query('payGapProfiles')
      .withIndex('by_user', (q: any) => q.eq('userId', user._id))
      .order('desc')
      .first()

    const now = Date.now()
    const caseFileId = await ctx.db.insert('caseFiles', {
      userId: user._id,
      title: '', // The action fills this in after generation.
      status: 'generating',
      language: user.preferredLanguage,
      payGapProfileId: payGapProfile?._id,
      createdAt: now,
      updatedAt: now,
    })

    await ctx.scheduler.runAfter(0, internal.caseFileAction.generateCaseFileInternal, {
      caseFileId,
      userId: user._id,
      language: user.preferredLanguage,
    })

    return caseFileId
  },
})

/**
 * Generate (or regenerate) the public share token for a case file.
 * Returns the token so the client can build the share URL.
 */
export const generateShareToken = mutation({
  args: { caseFileId: v.id('caseFiles') },
  handler: async (ctx, args): Promise<string> => {
    const user = await requireUser(ctx as any)

    const cf = await ctx.db.get(args.caseFileId)
    if (!cf || cf.userId !== user._id) throw new Error('Case file not found.')
    if (cf.status !== 'ready') throw new Error('Case file is not ready yet.')

    // Return existing token if already generated.
    if (cf.shareToken) return cf.shareToken

    // Build a collision-resistant token without relying on external crypto.
    const token = `cf_${Date.now().toString(36)}_${Math.random().toString(36).slice(2)}_${Math.random().toString(36).slice(2)}`

    await ctx.db.patch(args.caseFileId, {
      shareToken: token,
      updatedAt: Date.now(),
    })

    return token
  },
})

/**
 * Delete a case file owned by the calling user.
 */
export const deleteCaseFile = mutation({
  args: { caseFileId: v.id('caseFiles') },
  handler: async (ctx, args) => {
    const user = await requireUser(ctx as any)

    const cf = await ctx.db.get(args.caseFileId)
    if (!cf || cf.userId !== user._id) throw new Error('Case file not found.')

    await ctx.db.delete(args.caseFileId)
    return { deleted: true }
  },
})

// ---------------------------------------------------------------------------
// Internal mutations (called from caseFileAction — not exposed to the client)
// ---------------------------------------------------------------------------

export const saveBrief = internalMutation({
  args: {
    caseFileId: v.id('caseFiles'),
    title: v.string(),
    brief: v.any(),
    includedWinIds: v.array(v.id('wins')),
    geminiModelUsed: v.string(),
    promptTokens: v.optional(v.number()),
    completionTokens: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.caseFileId, {
      title: args.title,
      status: 'ready',
      brief: args.brief,
      includedWinIds: args.includedWinIds,
      geminiModelUsed: args.geminiModelUsed,
      promptTokens: args.promptTokens,
      completionTokens: args.completionTokens,
      updatedAt: Date.now(),
    })
  },
})

export const markCaseFileError = internalMutation({
  args: {
    caseFileId: v.id('caseFiles'),
    errorMessage: v.string(),
  },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.caseFileId, {
      status: 'error',
      errorMessage: args.errorMessage,
      updatedAt: Date.now(),
    })
  },
})
